version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "9010:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:9011

  backend:
    build:
      context: ./backend
    ports:
      - "9011:9011"
    environment:
      - GIN_MODE=release
      - PORT=9011

volumes:
  db_data: 