version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "9010:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://localhost:9011

  backend:
    build:
      context: ./backend
    ports:
      - "9011:9011"
    depends_on:
      - mongodb
    environment:
      - GIN_MODE=release
      - PORT=9011
      - MONGO_URI=mongodb://mongodb:27017/pryzm
    
  mongodb:
    image: mongo:latest
    ports:
      - "27027:27017"
    volumes:
      - db_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pryzm

volumes:
  db_data: 